pipeline{
    agent any
	
	stages{
	  stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn compile 
    '''
		    }
	    }
	    
	    stage('QA test Stage'){
			steps{
					sh '''
          cd StudentTest
          mvn clean test package sonar:sonar
    '''
				}
		    }
		     stage('Junit test Stage'){
			steps{
				
				junit 'StudentTest/target/surefire-reports/*.xml'
		    }
	    }
	  stage('ansible-deploy'){
	      steps{
	          ansiblePlaybook credentialsId: 'ansible-privateKey', disableHostKeyChecking: true, installation: 'ansible', inventory: 'StudentTest/dev.inv', playbook: 'StudentTest/Test.yml'
	      }
	  }
	    
	}
}
