pipeline{
    agent any
	
	stages{
	  stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentHandson
          mvn compile 
    '''
		    }
	    }
	    
	    stage('QA test Stage'){
			steps{
					sh '''
          cd StudentHandson
          mvn clean test package sonar:sonar
    '''
				}
		    }
		     stage('Junit test Stage'){
			steps{
				
				junit 'StudentHandson/target/surefire-reports/*.xml'
		    }
	    }
	    stage('Junit test Stage'){
			steps{
				
				nexusArtifactUploader artifacts: [[artifactId: 'StudentTest', classifier: '', file: 'StudentTest/target/StudentTest-0.0.1-SNAPSHOT.war', type: 'war']], credentialsId: 'nexus', groupId: 'st', nexusUrl: '192.168.56.108:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'http://192.168.56.108:8081/repository/student-sample/', version: '0.0.1-SNAPSHOT'
		    }
	    }
	  stage('ansible-deploy'){
	      steps{
	          echo "ansible"
	      }
	  }
	    
	}
}
