pipeline{
    agent any
	
	  stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn compile 
    '''
		    }
	    }
	     stage('Junit test Stage'){
			steps{
				
				echo "juint"
		    }
	    }
	    stage('QA test Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn clean test package sonar:sonar
    '''
		    }
	    }
	  stage('ansible-deploy'){
	      steps{
	          ansiblePlaybook credentialsId: 'Ansible', disableHostKeyChecking: true, installation: 'AnsibleTest', inventory: 'StudentTest/dev.inv', playbook: 'StudentTest/Test.yml'
	      }
	     
	  }
	    
	}
	 post{
	  	always{
	  	 	junit 'StudentTest/target/surefire-reports/*.xml'
	  	 }
	  	}
	 
}